# CMake generated Testfile for 
# Source directory: C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc
# Build directory: C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(soci_odbc_test_access "C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/bin/soci_odbc_test_access" "FILEDSN=C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/test-access.dsn" "--invisibles")
set_tests_properties(soci_odbc_test_access PROPERTIES  _BACKTRACE_TRIPLES "C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/cmake/SociBackend.cmake;353;add_test;C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/CMakeLists.txt;14;soci_backend_test;C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/CMakeLists.txt;0;")
add_test(soci_odbc_test_access_static "C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/bin/soci_odbc_test_access_static" "FILEDSN=C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/test-access.dsn" "--invisibles")
set_tests_properties(soci_odbc_test_access_static PROPERTIES  _BACKTRACE_TRIPLES "C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/cmake/SociBackend.cmake;375;add_test;C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/CMakeLists.txt;14;soci_backend_test;C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/CMakeLists.txt;0;")
add_test(soci_odbc_test_mssql "C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/bin/soci_odbc_test_mssql" "FILEDSN=C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/test-mssql.dsn" "--invisibles")
set_tests_properties(soci_odbc_test_mssql PROPERTIES  _BACKTRACE_TRIPLES "C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/cmake/SociBackend.cmake;353;add_test;C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/CMakeLists.txt;24;soci_backend_test;C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/CMakeLists.txt;0;")
add_test(soci_odbc_test_mssql_static "C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/bin/soci_odbc_test_mssql_static" "FILEDSN=C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/test-mssql.dsn" "--invisibles")
set_tests_properties(soci_odbc_test_mssql_static PROPERTIES  _BACKTRACE_TRIPLES "C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/cmake/SociBackend.cmake;375;add_test;C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/CMakeLists.txt;24;soci_backend_test;C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/CMakeLists.txt;0;")
add_test(soci_odbc_test_mysql "C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/bin/soci_odbc_test_mysql" "FILEDSN=C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/test-mysql.dsn" "--invisibles")
set_tests_properties(soci_odbc_test_mysql PROPERTIES  _BACKTRACE_TRIPLES "C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/cmake/SociBackend.cmake;353;add_test;C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/CMakeLists.txt;31;soci_backend_test;C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/CMakeLists.txt;0;")
add_test(soci_odbc_test_mysql_static "C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/bin/soci_odbc_test_mysql_static" "FILEDSN=C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/test-mysql.dsn" "--invisibles")
set_tests_properties(soci_odbc_test_mysql_static PROPERTIES  _BACKTRACE_TRIPLES "C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/cmake/SociBackend.cmake;375;add_test;C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/CMakeLists.txt;31;soci_backend_test;C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/CMakeLists.txt;0;")
add_test(soci_odbc_test_postgresql "C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/bin/soci_odbc_test_postgresql" "FILEDSN=C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/test-postgresql-win64.dsn" "--invisibles")
set_tests_properties(soci_odbc_test_postgresql PROPERTIES  _BACKTRACE_TRIPLES "C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/cmake/SociBackend.cmake;353;add_test;C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/CMakeLists.txt;43;soci_backend_test;C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/CMakeLists.txt;0;")
add_test(soci_odbc_test_postgresql_static "C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/bin/soci_odbc_test_postgresql_static" "FILEDSN=C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/test-postgresql-win64.dsn" "--invisibles")
set_tests_properties(soci_odbc_test_postgresql_static PROPERTIES  _BACKTRACE_TRIPLES "C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/cmake/SociBackend.cmake;375;add_test;C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/CMakeLists.txt;43;soci_backend_test;C:/Programming/HoseoServer/HoseoServer/trd/SOCI/soci-4.0.3/tests/odbc/CMakeLists.txt;0;")
